@id=
@productId=

###

GET {{base_url}}/v1/carts/me
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/carts/items
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "items": [
    {
      "productId": "",
      "quantity": 1
    }
  ]
}

###

DELETE {{base_url}}/v1/carts/items
Authorization: Bearer {{access_token}}

###

DELETE {{base_url}}/v1/carts/items/{{id}}
Authorization: Bearer {{access_token}}
