@id=
@productId=

###

GET {{base_url}}/v1/carts/me
Authorization: Bearer {{access_token}}

###

DELETE {{base_url}}/v1/carts/items
Authorization: Bearer {{access_token}}

###

POST {{base_url}}/v1/carts/items
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "productId": "{{productId}}",
  "quantity": 0
}

###

PATCH {{base_url}}/v1/carts/items/quantity
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "id": "{{id}}",
  "quantity": 0
}

###

DELETE {{base_url}}/v1/carts/items/{{id}}
Authorization: Bearer {{access_token}}
