@id=

###

GET {{base_url}}/v1/products/search
Authorization: Bearer {{access_token}}

###

PUT {{base_url}}/v1/products
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Product 5",
  "description": "",
  "price": 50000,
  "stock": 100
}


###

GET {{base_url}}/v1/products/{{id}}
Authorization: Bearer {{access_token}}
